name: CI
on: [workflow_dispatch, push]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Theos
        uses: resources/setup-theos@v1

      - name: Download iOS SDK
        run: |
          mkdir -p $THEOS/sdks
          curl -LO https://github.com/theos/sdks/raw/master/iPhoneOS14.5.sdk.tar.xz
          tar -xf iPhoneOS14.5.sdk.tar.xz -C $THEOS/sdks
          rm iPhoneOS14.5.sdk.tar.xz

      - name: Build Tweak
        run: |
          make package FINALPACKAGE=1 ARCHS="arm64"
        
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: FBAutoTool-Final
          path: packages/*.deb
